version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/codepipeline/project/react-django-app

permissions:
  - object: /home/ubuntu/codepipeline/project/react-django-app
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deployapp.sh
      timeout: 3000
      runas: ubuntu
