version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/codepipeline/project/react-django-app
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/deployapp.sh
      timeout: 3000
      runas: ubuntu
