version: 1.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/codepipeline/project/react-django-app
    overwrite: true

permissions:
  - object: /home/ubuntu/codepipeline/project/react-django-app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
      - directory

hooks:
  ApplicationStart:
    - location: /home/ubuntu/codepipeline/project/react-django-app/deployapp.sh
      timeout: 3000
      runas: ubuntu
