version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/codepipeline/project/react-django-app

permissions:
  - object: /home/ubuntu/codepipeline/project/react-django-app
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/cleaninstance.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/boot.sh
      timeout: 300
      runas: ubuntu

