version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/codepipeline/project/react-django-app/
file_exists_behaviour: OVERWRITE
hooks:
  BeforeInstall:
    - location: scriptsss/deployapp.sh
      timeout: 3000
      runas: ubuntu
