version: 0.0
os: linux

files:
  - source: /
    destination: /
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/deployapp.sh
      timeout: 3000
      runas: ubuntu
