version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/codepipeline/project/react-django-app
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/codepipeline/project/react-django-app
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: /home/ubuntu/codepipeline/project/react-django-app/deployapp.sh
      timeout: 3000
