version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/codepipeline/project/react-django-app
hooks:
  AfterInstall:
    - location: deployapp.sh
      timeout: 300
      runas: root
