name: CI/CD pipeline for S3
on:
  push:
    branches:
      - s3-frontend
jobs:
  build:
    name: Checkout and Deploy Source Code
    runs-on: self-hosted
    environment: Env
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Deploy Source Code to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_EC2_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_EC2_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOYMENT_EC2_USER }}
          TARGET: /home/ubuntu
  deploy-app:
    name: Deploy Backend on EC2
    needs: deploy-frontend
    runs-on: self-hosted
    environment: Env
    steps:
      - name: Deploy and Run Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_EC2_HOST_DNS }}
          username: ${{ secrets.DEPLOYMENT_EC2_USER }}
          key: ${{ secrets.DEPLOYMENT_EC2_KEY }}
          script: |
            cd /home/ubuntu/project/react-django-app
            git checkout s3-frontend
            git pull origin s3-frontend
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker rmi $(docker images -q)
            docker system prune -f
            docker compose pull
            docker compose up -d --build

  deploy-frontend:
    name: Deploy Frontend to S3
    needs: build
    runs-on: self-hosted
    environment: Env
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      # - name: Deploy static site to S3 bucket
      #   run: |
      #     git fetch --all
      #     git checkout s3-frontend
      #     git pull origin s3-frontend
      #     npm i
      #     npm run build
      #     pwd
      #     aws s3 sync /home/ubuntu/_work/react-django-app/react-django-app/client/build/ s3://${{ secrets.AWS_S3_BUCKET }}
      - name: Build Frontend
        run: |
          cd /home/ubuntu/_work/react-django-app/react-django-app/client/ 
          npm install
          npm run build
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          SOURCE_DIR: /home/ubuntu/_work/react-django-app/react-django-app/client/build/
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}